namespace: dev
name: predict-service

labels:
  app: predict-service

containers:
  name: bert-fastapi
  image:
    repository: freiderich/bert-fastapi-image
    tag: 703a6fe1e61a6b080363bfb12d88208c0f01f2ee
  resources:
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 3Gi
      cpu: 2
  http_port: 8000

service:
  type: ClusterIP
  ports:
    port: 8000
    targetPort: 8000
