# Stage 1: Build stage
FROM python:3.12.10-slim as builder
FROM pytorch
WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip \
 && pip install --prefix=/install \
 --no-cache-dir -r requirements.txt
 
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir transformers==4.51.3

# Stage 2: Runtime stage
FROM python:3.12.10-slim
WORKDIR /app

COPY --from=builder /install /usr/local
COPY . .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]